---
version: 2
jobs:
  release:
    docker:
      - image: timberio/docker-builder:1.0.0
    working_directory: /opt/packer-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image
          command: |
            VERSION=$(cat VERSION)
            docker build -t timberio/packer:$VERSION ./
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push timberio/packer:$VERSION

workflows:
  version: 2
  build:
    jobs:
      - release:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
